/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExogressClient */

#ifndef _Included_ExogressClient
#define _Included_ExogressClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExogressClient
 * Method:    spawn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ExogressClient_spawn
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
